### ISSUE TITLE
build.sh: don't continue on error

### ISSUE THREAD

**Issue by lt-holman** [Wind-River/device-cloud-lib#105]
The build.sh will continue even if there is an error building a dependency...  Thus, if an error in encountered it can be hard to determine to root cause.  The script should break on the first error.

This is related to issue #92 , as it would show the true reason for the failure.

**Comment by montagao** [comment]
I think we can add a bash option for this by adding  `set -e` to the top of the `build.sh` script, this causes the script to exit if any subsequent commands exit with a non-zero status, excluding logic paths

From man bash:
> The shell does not exit if the command that fails is part of the command list immediately following a while or until keyword, part of the test following the if or elif reserved words, part of any command executed in a && or || list except the command following the final && or ||, any command in a pipeline but the last, or if the command's return value is being inverted with !`
