### ISSUE TITLE
iot.cfg.example in github is invalid

### ISSUE THREAD

**Issue by rhage1118** [Wind-River/device-cloud-lib#109]
The file needed to run device-manager (iot.cfg) needs to be updated since it is invalid JSON format.  Word "True" should be "true" to be valid JSON.  

https://github.com/Wind-River/device-cloud-lib/blob/master/src/device-manager/iot.cfg.example

Also, are all the fields supported in the cfg file?

Thanks...

**Comment by element-82** [comment]
Correct.  That is the python version.
