### ISSUE TITLE
iot-device-manager:  Segmentation fault (core dumped)  MQTT port 1883

### ISSUE THREAD

**Issue by rhage1118** [Wind-River/device-cloud-lib#110]
Seeing a core dump (seg fault) when port 1883 is used (with MQTT default library: PAHO).

/etc/iot/iot-connect.cfg:

{
  "cloud": {
    "host": "core-api.hdcstg.net",
    "port": 1883,
    "token": "uGGvfXcJEouglJ0p"
  },
  "validate_cloud_cert": true,
  "ca_bundle_file": "/etc/ssl/certs/ca-certificates.crt",
  "log_level": "all"
}

RUN the executable with the cfg file above to see the error.

-----------------------------------------
rhage@yow-rhage-v1: /tmp/iot-test/deps/device-cloud-lib/build/install/local/bin$ ./iot-device-manager 
Starting Device Manager
  * Checking for configuration file iot.cfg ...
  * Setting default runtime dir to /var/lib/iot
  * Reading config file /etc/iot/iot.cfg
Device id: 3b284c80-bcb1-4bc8-bd74-ae1f5bf9e4fc

Info - iot_base.c:297 - Looking for configuration file: /etc/iot/iot-connect.cfg
Current Configuration:
cloud.host: core-api.hdcstg.net
cloud.port: 1883
cloud.token: uGGvfXcJEouglJ0p
validate_cloud_cert: true
ca_bundle_file: /etc/ssl/certs/ca-certificates.crt
log_level: all
Info - iot_base.c:297 - Looking for configuration file: /etc/iot/device-manager.cfg
Current Configuration:
cloud.token: uGGvfXcJEouglJ0p
Trace - tr50.c:1328 - tr50: execute 6.0
Trace - tr50.c:1328 - tr50: execute 6.1
Trace - tr50.c:1045 - tr50: connect
Segmentation fault (core dumped)

**Comment by element-82** [comment]
Looks like an SSLSocket_createContext is called in the api:
(gdb) bt
#0  0x00007ffff7b0dc8e in SSLSocket_createContext () from /home/pb/hdc/device-cloud-lib/junk/lib/libiot.so.18
#1  0x00007ffff7b0df86 in SSLSocket_setSocketForSSL () from /home/pb/hdc/device-cloud-lib/junk/lib/libiot.so.18
#2  0x00007ffff7b0bf9b in MQTTAsync_connecting () from /home/pb/hdc/device-cloud-lib/junk/lib/libiot.so.18
#3  0x00007ffff7b0c4ef in MQTTAsync_cycle () from /home/pb/hdc/device-cloud-lib/junk/lib/libiot.so.18
#4  0x00007ffff7b08ead in MQTTAsync_receiveThread () from /home/pb/hdc/device-cloud-lib/junk/lib/libiot.so.18
#5  0x00007ffff6cd87fc in start_thread (arg=0x7fffed684700) at pthread_create.c:465
#6  0x00007ffff735ab5f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

**Comment by montagao** [comment]
issue with PAHO library.
