### ISSUE TITLE
Unit tests for alarm segfaulting

### ISSUE THREAD

**Issue by element-82** [Wind-River/device-cloud-lib#28]
Test project /home/pb/hdc/hdc-lib/t1
    Start 1: test-api-iot_alarm
1/8 Test #1: test-api-iot_alarm ...............***Exception: SegFault  0.08 sec
[==========] Running 15 test(s).
[ RUN      ] test_iot_alarm_register_empty
[       OK ] test_iot_alarm_register_empty
[ RUN      ] (null)
Test failed with exception: Illegal instruction

[  FAILED  ] (null)
[ RUN      ] (null)
Could not run the test - check test fixtures
[  ERROR   ] (null)
[ RUN      ] (null)

    Start 2: test-api-iot_base
2/8 Test #2: test-api-iot_base ................***Exception: SegFault  0.08 sec
[==========] Running 46 test(s).
[ RUN      ] test_iot_config_get_not_found
[       OK ] test_iot_config_get_not_found
[ RUN      ] (null)
Test failed with exception: Segmentation fault

[  FAILED  ] (null)
[ RUN      ] (null)

    Start 3: test-api-iot_base64
3/8 Test #3: test-api-iot_base64 ..............***Exception: Illegal  0.08 sec
[==========] Running 15 test(s).
[ RUN      ] test_iot_base64_decode_bad_string
[       OK ] test_iot_base64_decode_bad_string
[ RUN      ] (null)
Could not run the test - check test fixtures
[  ERROR   ] (null)
[ RUN      ] (null)
Could not run the test - check test fixtures
[  ERROR   ] (null)
[ RUN      ] (null)

    Start 4: test-api-iot_common
4/8 Test #4: test-api-iot_common ..............***Exception: Illegal  0.08 sec
[==========] Running 179 test(s).
[ RUN      ] test_iot_common_arg_get_fail_convert
[       OK ] test_iot_common_arg_get_fail_convert
[ RUN      ] (null)
Test failed with exception: Illegal instruction

[  FAILED  ] (null)
[ RUN      ] (null)
Could not run the test - check test fixtures
[  ERROR   ] (null)
[ RUN      ] (null)

    Start 5: test-api-iot_json_decode
5/8 Test #5: test-api-iot_json_decode .........***Exception: SegFault  0.08 sec
[==========] Running 75 test(s).
[ RUN      ] test_iot_json_decode_array_at_invalid
[       OK ] test_iot_json_decode_array_at_invalid
[ RUN      ] (null)
Test failed with exception: Segmentation fault

[  FAILED  ] (null)
[ RUN      ] (null)
Could not run the test - check test fixtures
[  ERROR   ] (null)
[ RUN      ] (null)

    Start 6: test-api-iot_json_encode
6/8 Test #6: test-api-iot_json_encode .........***Exception: Illegal  0.08 sec
[==========] Running 75 test(s).
[ RUN      ] test_iot_json_encode_array_end_at_root
[       OK ] test_iot_json_encode_array_end_at_root
[ RUN      ] (null)
Could not run the test - check test fixtures
[  ERROR   ] (null)
[ RUN      ] (null)
Could not run the test - check test fixtures
[  ERROR   ] (null)
[ RUN      ] (null)

    Start 7: test-api-iot_location
7/8 Test #7: test-api-iot_location ............***Exception: SegFault  0.08 sec
[==========] Running 27 test(s).
[ RUN      ] test_iot_location_accuracy_set
[       OK ] test_iot_location_accuracy_set
[ RUN      ] (null)
Could not run the test - check test fixtures
[  ERROR   ] (null)
[ RUN      ] (null)
Could not run the test - check test fixtures
[  ERROR   ] (null)
[ RUN      ] (null)

    Start 8: test-api-iot_telemetry
8/8 Test #8: test-api-iot_telemetry ...........***Exception: SegFault  0.08 sec
[==========] Running 41 test(s).
[ RUN      ] test_iot_telemetry_allocate_empty
[       OK ] test_iot_telemetry_allocate_empty
[ RUN      ] (null)
Test failed with exception: Segmentation fault

[  FAILED  ] (null)
[ RUN      ] (null)

0% tests passed, 8 tests failed out of 8

Total Test time (real) =   0.64 sec

The following tests FAILED:
	  1 - test-api-iot_alarm (SEGFAULT)
	  2 - test-api-iot_base (SEGFAULT)
	  3 - test-api-iot_base64 (ILLEGAL)
	  4 - test-api-iot_common (ILLEGAL)
	  5 - test-api-iot_json_decode (SEGFAULT)
	  6 - test-api-iot_json_encode (ILLEGAL)
	  7 - test-api-iot_location (SEGFAULT)
	  8 - test-api-iot_telemetry (SEGFAULT)
Errors while running CTest
CMakeFiles/check.dir/build.make:57: recipe for target 'CMakeFiles/check' failed
make[3]: *** [CMakeFiles/check] Error 8
CMakeFiles/Makefile2:106: recipe for target 'CMakeFiles/check.dir/all' failed
make[2]: *** [CMakeFiles/check.dir/all] Error 2
CMakeFiles/Makefile2:113: recipe for target 'CMakeFiles/check.dir/rule' failed
make[1]: *** [CMakeFiles/check.dir/rule] Error 2
Makefile:186: recipe for target 'check' failed
make: *** [check] Error 2

**Comment by lt-holman** [comment]
this is caused by multiple cmocka installations (both using apt-get & downloading and installing the package)... remove the older 1.
