### ISSUE TITLE
ota uses only the global store by default

### ISSUE THREAD

**Issue by element-82** [Wind-River/device-cloud-lib#31]
Trace - tr50.c:1312 - -->{"2":{"command":"file.get","params":{"global":true,"fileName":"foo.tar.gz","thingKey":"4b83cf19-4e7d-477f-8b6c-4985eb36b059-device-manager"}}}

Note: the foo.tar.gz archive is in the "files" section, not the global store.  Need to add a parameter in the thing def to use global or not.

**Comment by montagao** [comment]
thing def updated
