### ISSUE TITLE
Some methods defined in the device manager thing definition don't work

### ISSUE THREAD

**Issue by jkeffer** [Wind-River/device-cloud-lib#33]
The Python and C implementations of the device manager should be able to use the same thing definition and support all elements of it unless there is a technical limitation for a specific element. I found the following issues with the C agent. There may be issues with other methods as well.

- Quit App returns     "not found".

- Reset agent returns    "execution error". On the device it returns the following:
Debug - iot_action.c:1259 - Executing action: reset_agent
Debug - iot_action.c:790 - Executing command: sudo ./iot-control --restart
Info - iot_action.c:829 - Command "reset_agent", exited with: 1
Debug - tr50.c:1828 - tr50: received (22 bytes on reply): {"8":{"success":true}}

**Comment by lt-holman** [comment]
these actions have now been added on the supported operating systems.
