### ISSUE TITLE
Applications can't connect to Device Cloud over port 443

### ISSUE THREAD

**Issue by jkeffer** [Wind-River/device-cloud-lib#44]
I run the device manager on Ubuntu 16.04 with port 443 specified in the connection configuration file and get the following:

Current Configuration:
cloud.host: core-api.hdcstg.net
cloud.port: 443
cloud.token: DQyeagrsRgbs8lwL
validate_cloud_cert: true
Error - tr50.c:953 - tr50: failed to connect
Error - iot_base.c:371 - Failed to connect
Info - device_manager_main.c:1160 - Failed to connect

Failed to initialize device-manager

I have the same problem with the sample apps, although they fail silently. 

Port 8883 works fine.

**Comment by lt-holman** [comment]
This depends on support in the underlying libraries we use for cloud connections... Paho or Mosquitto... Currently, I've put in a patch to paho for this support... I will have to look into implementing it into mosquitto.
