### ISSUE TITLE
Thing defs and apps are required in the cloud for the sample applications.

### ISSUE THREAD

**Issue by jkeffer** [Wind-River/device-cloud-lib#50]
Issue https://github.com/Wind-River/device-cloud-python/issues/94 tracks this issue because it has the setup-cloud-deps.py script. I'm opening it here for visibility in case the cloud setup functionality is kept somewhere else. 

The sample apps are not useful without the thing defs. The simple apps are a subset of the complete app, so all could use a single thing def that covers the complete app.

**Comment by lt-holman** [comment]
thing defs are now the same as python.
